### ISSUE TITLE
Support custom URLs

### ISSUE THREAD

**Issue by leofidus** [jaymoulin/bandcamp-down-chrome-ext#1]
Bandcamp allows Pro users to set up custom domains (https://bandcamp.com/help/custom_domain). One example would be http://music.disasterpeace.com/album/fez-ost

It would be great if there was a way to support these. Maybe an option in the extension's menu to manually trigger an action?

Other than this, this extension is great! Keep up the good work.

**Comment by jaymoulin** [comment]
It will be available on Chrome Webstore in few minutes

**Comment by leofidus** [comment]
That was fast and it works great. Thanks :)
