### ISSUE TITLE
Someway of continue downloading a discography

### ISSUE THREAD

**Issue by e200** [jaymoulin/bandcamp-down-chrome-ext#11]
Can you bring to us a way to get back the to the progress of a **discography** download?

I tried to download a **discography** but it stucks while downloading the **albums**, i don't know why, but thats not a problem with my Internet connection.

When it stucks, i stop it, but, if i try again, it downloads **albums** already downloaded.

**Comment by jaymoulin** [comment]
I think you can restart all downloadable tracks by accessing the option Menu (right click on extension > Options) (chrome-extension://nmoobgpmablfmgchfjnhkbloaobiogeh/options.html).

You should have an option to retry all.

**Comment by e200** [comment]
Sorry, i didn't  saw that option before.

Thank you!
