### ISSUE TITLE
Bug! A bug downloading a discography

### ISSUE THREAD

**Issue by e200** [jaymoulin/bandcamp-down-chrome-ext#12]
**Discography** not downloading on click **notification**.

[1.mkv.zip](https://github.com/jaymoulin/bandcamp-down-chrome-ext/files/1207489/1.mkv.zip)

**Comment by jaymoulin** [comment]
Just bad luck. You tried this url : https://atjazzrecordcompany.bandcamp.com/music which is not available anymore. They moved to https://atjazz.bandcamp.com/music which seems to work better

**Comment by e200** [comment]
No man, it's really a bug, they moved a week ago.

See the video, i recorded that video before they moved to another url.

**Comment by e200** [comment]
Think with me :)

If you're right, why i get a notification of an available discography if there's no available discography for that link?

**Comment by jaymoulin** [comment]
When you go on a discography page, all albums discovered are added to the album downloadable list (with all other pages). Then, the artist is extracted from that page and all album matching this artist are downloaded.

This means that if the artist on the discography page differs from albums, you can't download the album. So, the following behavior occurs :
- You get notified that a discography is downloadable for "Atjazz record company"
- All albums discovered match "Atjazz" thus not matching "Atjazz record company"
- You start download for "Atjazz record company"
- No album downloaded = normal behavior

Anyway, you can still manage your downloads on the option page : (chrome-extension://nmoobgpmablfmgchfjnhkbloaobiogeh/options.html)

**Comment by jaymoulin** [comment]
I forced the artist to avoid the problem. The 0.4.2 version should be available on Chrome webstore soon

**Comment by e200** [comment]
. Many Thanks.
