### ISSUE TITLE
Error while trying to install ext

### ISSUE THREAD

**Issue by e200** [jaymoulin/bandcamp-down-chrome-ext#14]
![captura de ecra de 2017-08-28 10-39-00](https://user-images.githubusercontent.com/20504726/29768163-22b9cdc2-8bdd-11e7-8c58-ab1e2399c852.png)

Invalid package. Details "Cannot load background script "js/dist/FileSaver.min.js".".

**Comment by jaymoulin** [comment]
Explains a lot of things... I'll handle that ASAP
