### ISSUE TITLE
bandcamp download chrome ext 0.4.4 not working on bandcamp.

### ISSUE THREAD

**Issue by pHROZEN-gHOST** [jaymoulin/bandcamp-down-chrome-ext#15]
A couple of weeks ago I noticed that the application no longer works on bandcamp.
I assumed that this would be a common problem with others and that it would get fixed. 
So, rather than be a part of the crowd, I waited for an update. It's still not working.
I am on Windows 10 Pro with all updates and the latest Chrome.
There is a dialog, like the download prompt, which says "{album name} error while downloading" .
This happens for each song in an album. It happens with all attempts to download.

Did BC change something to make it not work?

**Comment by jaymoulin** [comment]
Do you have any URL to reproduce this issue? I don't seem to have any problem.

Please also notice that this extension is actually in a selling process and may have changes, support changes or discontinued maintenance.

**Comment by pHROZEN-gHOST** [comment]
I cannot get ANY bandcamp stored music to work.
It could be an issue on my end ..for example a recent update to uBlock Origin that prevents something from connecting.
I'm gong to disable other addons just to see if I can get it to work again. If I find a culprit, I will point it out.

**Comment by pHROZEN-gHOST** [comment]
OK, I disabled ALL extensions except for yours. I still cannot download from bandcampHere's a url ... 
        Shower Talk, by Anna Jean


  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Shower Talk, by Anna Jean
 8 track album  |   |

  |

  |

 

My next step is to turn off the firewall and virus scanner.

**Comment by jaymoulin** [comment]
Still no problem:

```
[jay:~/Downloads] 2s $ l
total 47M
drwxr-xr-x  2 jay jay 4,0K sept. 26 20:53 .
drwxr-xr-x 31 jay jay 4,0K sept. 26 19:11 ..
-rw-rw-r--  1 jay jay  47M sept. 26 20:51 Anna Jean - Shower Talk.zip
```

URL used to reproduce : https://annajean.bandcamp.com/album/shower-talk

**Comment by pHROZEN-gHOST** [comment]
I wonder if Bandcamp is blocking my IP address  :-(

**Comment by jaymoulin** [comment]
Bandcamp blocks some requests when you make too many calls, but you can occasionally retry them in the extension options : [chrome-extension://nmoobgpmablfmgchfjnhkbloaobiogeh/options.html](chrome-extension://nmoobgpmablfmgchfjnhkbloaobiogeh/options.html)

**Comment by mmmxnv** [comment]
Hello, for two days that the application does not let me download any kind of music, what is the problem? :(

**Comment by jaymoulin** [comment]
What is your problem? URL to reproduce? Version?

**Comment by mmmxnv** [comment]
the first time i tried to download this https://brockbeats.bandcamp.com/album/chilled-rooms 
but when it will download, I get many errors that say "error while downloading!".
and i think the version is 0.4.3

**Comment by jaymoulin** [comment]
As I explained just before your post, Bandcamp blocks some requests when you make too many calls, but you can occasionally retry them in the extension options : chrome-extension://nmoobgpmablfmgchfjnhkbloaobiogeh/options.html

**Comment by neil3011** [comment]
i am also getting error while downloading file. worked fine only about 30 mins ago but now the album i want to download is 'waiting' and i cant retry it

**Comment by mmmxnv** [comment]
try to re-download it in this link, but I still see the same mistakes

**Comment by neil3011** [comment]
nope still same problem

**Comment by DevoRedxx** [comment]
Yeah same here, its not working on my PC. I even tried it on my Laptop and its still not working. Is there any way to use this again or is it over?

**Comment by pHROZEN-gHOST** [comment]
This extension used to work like a charm every time I used it. Something has changed. Now it fails every time.

**Comment by mmmxnv** [comment]
I hope this is solved

**Comment by jaymoulin** [comment]
As you can see in commits, nothing has changed. Bandcamp always blocked request and that's why I implemented the download manager in 0.3.0. 

If the extension detects album and tracks, this means the issue you're having is not related with the way that pages are generated by bandcamp.

It might have a security added to avoid download of files but, it that were the case, I would be able to reproduce the problem which I can't.

As I said in the latest update, this extension is in a selling process, thus, I will not look further *for the moment* until the extension is sold or not.

In the case the extension is sold, I will not be part of support anymore and you'll have to see with the new development team. In the other case, I'll probably add a message to explain what happened in case an error occurs and/or a download timeout.

P.S. @mmmxnv I was able to reproduce your issue with your URL. If I have a little time, I will check to see what happens for this URL, but still, you have to notice that I will probably won't be part of the dev team anytime soon.

**Comment by aquaeous** [comment]
is there anyway somebody can donate so the issue can be looked at, im getting an error as well

**Comment by pHROZEN-gHOST** [comment]
I think the issue may be something more subtle. Knowing what the "error" is would be helpful. 

For example, the extension may be timing out for some of us while it is not for you ... because of differences in the network which we are dealing with. i.e. you may not have as many hops to get to the source. Just a guess tho'.

**Comment by e200** [comment]
After read the comments and test the extension, i conclude that something goes wrong, not in the developer side, but its appear to be some changes on the Bandcamp server.

My extension always worked fine, until i check today.

Its doesn't take any time to fail, it fail immediately.

**Comment by jaymoulin** [comment]
I can confirm that. But as explained earlier, I'm in a selling process and will not be part of the dev team anymore. This should be handled by the new dev team. I'm just waiting confirmation that the transaction is done to close the project

**Comment by jaymoulin** [comment]
Extension has been sold to quotetab.com. You can contact them at support@quotetab.com
You can still donate me to continue making great extensions :
[![Bitcoin donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/btc.png "Bitcoin donation")](https://m.freewallet.org/id/374ad82e/btc)
[![Litecoin donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ltc.png "Litecoin donation")](https://m.freewallet.org/id/374ad82e/ltc)

Also, for unknown reason, the new dev team reintegrated support to this github and my paypal donation button, so feel free to donate me :)

**Comment by jaymoulin** [comment]
The selling process of this extension turned extremely bad and the new acquirer refuses to pay what's due. The new acquirer said it will not fix the issue. As a result I will not publish sources anymore publicly and will probably start over again. 

Please consider making donation so we could make a great extension together.

[![Bitcoin donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/btc.png "Bitcoin donation")](https://m.freewallet.org/id/374ad82e/btc)
[![Litecoin donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ltc.png "Litecoin donation")](https://m.freewallet.org/id/374ad82e/ltc)
