### ISSUE TITLE
Soundcloud shows deep code on hover

### ISSUE THREAD

**Issue by mmmmna** [jaymoulin/bandcamp-down-chrome-ext#18]
Logged into my Soundcloud account makes no difference.
Reference this Soundcloud link
https://soundcloud.com/off-limits/off-limits-100k-likes-mix-free-download

KeepTune extension enabled, shows lengthy tooltip when hovering on the page, looks like a 
list of segments with sequential numbering and the word asset, suffix .js
https://mega.nz/#!tJxEDZID!1v6DEfMBCKGV1WrSs281Xf7PSnm6zzXIqabpVFZq-HM

Disable KeepTune and refresh the page, I see normal Soundcloud hovers.
https://mega.nz/#!8RhCUIDa!yjPmROO1w-XWkX5Ymdd7gGyrjxK_D1-6UjG0-WcZ5TQ

NB: I'm using Slimjet, Version 16.0.5.0 (based on Chromium 61.0.3163.79) (Official Build) (64-bit), running on Antix 64 bit version 16.2

**Comment by jaymoulin** [comment]
Thanks for your report, I'm already aware of this bug and have a fix available but I'm working on many things at the moment to prepare a meaningful release instead of many bug-fixes

**Comment by mmmmna** [comment]
Coolness abounds, thanks for the email! Updated report a couple times
(browser and distro) if that helps any.

**Comment by jaymoulin** [comment]
I didn't see anything but this report

**Comment by mmmmna** [comment]
In the original post.
