### ISSUE TITLE
Discography d/l doesn't complete in interactive method

### ISSUE THREAD

**Issue by mmmmna** [jaymoulin/bandcamp-down-chrome-ext#19]
Keeptune 1.1.1, Slimjet browser 'Version 16.0.9.0 (based on Chromium 61.0.3163.79) (Official Build) (64-bit)'

Visited a netlabel on Bandcamp. NewRetroWave is an example, but issue is not exclusive to that discography.

Keeptune discovers there is a discography,
offers me a download discography alert,
when I quickly click the download discography alert, only a few of the discography releases that are shown on the web page will be offered to me for download,
the remainder of the discography never appear via alert method,
no further interaction with me, the user.

From that, had I not been curious and randomly discovered 'right click (Keeptune icon) - Options', I'd never have known there was a download queue for links not yet downloaded. The missing downloads are listed.

Thus, Keeptune does create a proper list, as seen under 'Options - Downloads'.

Suggest investigation of download list processing,
Suggest right click - help.

Thx.

**Comment by jaymoulin** [comment]
I don't get your point. What is your suggestion?

**Comment by mmmmna** [comment]
Well, I was suggesting that you might investigate how the discography
elements were pushed into a queue fully processed, and maybe see if all the
elements of a discography were actually presented to the user for
downloading. Possibly the messages for each element of the discography pop
under other like messages and simply time out? In any event, I have only
been able to click on less than a full discography, hence my bug report.

Also, I was suggesting that the right mouse button could be used to present
a minimal help message. How would it be captured exclusively by Keeptune?
Maybe when hovering over the Keeptune icon in the browser, add a menu item
for help?
