### ISSUE TITLE
Request for Granular (Track-based) control of starting, restarting, cancellation.

### ISSUE THREAD

**Issue by farazfp** [jaymoulin/bandcamp-down-chrome-ext#20]
Sometimes, certain tracks get stuck in the "waiting" state:

![image](https://user-images.githubusercontent.com/5468563/38893393-66c75ca4-429f-11e8-8a6c-a6a94bca4260.png)

and when this happens, there seems to be no way to let Keeptunes know that a timeout has occurred; the complication being that all that has been downloaded will be discarded if a new request for download is made by refreshing the main album page.

It would be great if a stop/restart (*not* pause/resume) button would be available for each track listed.
Thank you. 

(The screenshot was taken after waiting for almost half an hour. Any number of reasons could cause this, bad internet connectivity being the foremost.)

**Comment by jaymoulin** [comment]
Thank you for this issue. I'll try to handle it as soon as schedules allows it

**Comment by farazfp** [comment]
Stellar job, as always sir. The update works swimmingly. You rock! :1st_place_medal:

**Comment by jaymoulin** [comment]
Don't forget to star the repo ;)
