### ISSUE TITLE
Question Mark in Album Title Not Working

### ISSUE THREAD

**Issue by davetremblay** [jaymoulin/bandcamp-down-chrome-ext#22]
Hi, I've found that an album with a question mark in its title seems to not be working. Also earlier (I don't know if fixed now) there was some odd behaviour of the program whenever there was a "/" in a song title, and it wasn't working when the slash was in the artist name. Thanks!

**Comment by jaymoulin** [comment]
Should be fixed. Update in few hours. Reopen this issue if you think it isn't
