### ISSUE TITLE
Soundcloud doesn't activate Keeptune

### ISSUE THREAD

**Issue by mmmmna** [jaymoulin/bandcamp-down-chrome-ext#23]
Slimjet browser Version 19.0.4.0 (based on Chromium 66.0.3359.117) (Official Build) (64-bit).

Visit www.soundcloud.com

Log in.

Go to an artist, I used https://soundcloud.com/bynar

Scroll down to Music For The Mashes Vol. 3 Album

Play any track from the album.

Keeptune has not done anything, is greyed out.

Go to keeptune icon, click it, select options, click that.
"Downloads   Nothing to download for the moment!"

How does keeptune present files through the browser for downloading?

**Comment by jaymoulin** [comment]
The extension is behaving as expected. Maybe I should be clearer in the documentation on how it is supposed to work. You have to go to the `album` tab for the extension to detect albums. In your case : https://soundcloud.com/bynar/albums

**Comment by mmmmna** [comment]
Thanks for the clarification.

Following that link to https://soundcloud.com/bynar/albums, I eventually downloaded (after 6 minutes) the 4 available Bynar albums.

For the record, all 4 album dialogs pop in the exact same location onscreen, often on top of each other. We see one dialog versus knowing there are 4 albums. We click the visible dialog, and MAYBE a second dialog is waiting beneath it. Maybe about 5 seconds later, additional popups arrive in that exact same location. This can be confusing. Any chance to skew the album dialogs?

**Comment by jaymoulin** [comment]
I suggest you decide which notification should be displayed as only one notification for discography is shown. The notification system is built in Chrome.

chrome-extension://oidamlgjlcjhdpkflfefcemhmfpmlfbj/options.html#settings
