### ISSUE TITLE
Says downloaded, but where?

### ISSUE THREAD

**Issue by mmmmna** [jaymoulin/bandcamp-down-chrome-ext#24]
Ubuntu Mate 18.04 LTS for x64, Slimjet Version 19.0.4.0 (based on Chromium 66.0.3359.117) (Official Build) (64-bit)

Visit URL: https://newretrowave.bandcamp.com/album/the-chase-last-run
This album is downloadable!
Autostart enabled.
percentages increment to completion.
Downloaded message.
Nothing more.

Attached screenshot of my Keeptune settings
![screenshot at 2018-07-04 15-44-45](https://user-images.githubusercontent.com/31926804/42292552-59ef0722-7fa1-11e8-990d-c5bfa58c43c8.png)

NB: selecting one track from above URL, Keeptune download occurs and provides to me a window asking where to save. For above album session, no dialog asking where to save.

**Comment by jaymoulin** [comment]
Related to #22
