### ISSUE TITLE
Performance review

### ISSUE THREAD

**Issue by mmmmna** [jaymoulin/bandcamp-down-chrome-ext#26]
Keeptune 2.1.0
Flashpeak Slimjet, "Version 19.0.4.0 (based on Chromium 66.0.3359.117) (Official Build) (64-bit)"

Example link https://donpeyote.bandcamp.com/album/dreamcatcher
has 10 releases, at least 7 are captured by KeepTune, but I lost track while shutting them all down..

1] each album is presented via a popup message window.
1a] the popup window has a close button, I click it.
1b] tens of seconds go by, and a file-save dialog opens asking me to save a zip file.
1c] I close the file save dialog, I did not want to download the album.
2] another album is presented in a popup message window.
2a] the popup window has a close button, I click it.
2b] tens of seconds go by, and a file-save dialog opens asking me to save a zip file.
2c] I close the file save dialog, I did not want to download the album.

This continues until all the albums are presented.

Observations:

How do I tell KeepTune to not download albums?
What would I need to do for selecting a few but not all albums?
Why am I downloading files before I decide if I want to download them (server bandwidth, my data plan bandwidth limits)?

I suggest a rudimentary file picker is to be presented to the browser user before any content is actually downloaded.

Develop a list of the possible downloads,
present the list in a popup with radio buttons: radio for either yes download this entry or no download for this entry, default button is to be no download
Popup is then dismissable with the close button.
behind the scenes, after the popup is closed, parse the yes links and download them.
when a download is completed, present the file save dialog for each yes.
clean up list and continue with next download or conclude.

Save bandwidth, reduce annoyance, improve user experience.

**Comment by jaymoulin** [comment]
Go to options, Uncheck all options
Click Keeptune highlighted logo when you can download an album, You can see what is downloadable and what to download

**Comment by mmmmna** [comment]
Sorry, I see my curiosity isn't what it might have been.

So this:
Right click the Keeptune logo (it is highlighted when you can download something).
Click on Options in the menu that pops up.
Then click on Settings.
Adjust settings to your preferences.

Me: Download Autostart should be set to 'off' or 'left' or 'dark'.

Had I been more curious regarding the extension, I might have *looked* for settings.... Instead, it never occurred to me there were any settings to adjust.

Thanks for your patience.

**Comment by jaymoulin** [comment]
Thank you for precising the steps. This may help other users.
