### ISSUE TITLE
Include album cover files in the ZIP

### ISSUE THREAD

**Issue by Gimlao** [jaymoulin/bandcamp-down-chrome-ext#27]
In every Bandcamp pages, there are two cover files : a small one (700x700) and a big one (full size).

It would be nice to include both files in the ZIP. ❤️

**Comment by jaymoulin** [comment]
You already have the cover in each MP3 as an id3 tag but I think this is a good idea to add them in the zip as well due to different device support.

**Comment by Gimlao** [comment]
Actually, I don't see any covers in the id3 tags after downloading with KeepTune... =/

I always download the cover files and include them with Mp3tag or iTunes. '-'

**Comment by jaymoulin** [comment]
This will be available in few moments on chrome webstore in version 2.2.0.

Please donate, rate this extension (https://chrome.google.com/webstore/detail/keeptune-download-on-band/oidamlgjlcjhdpkflfefcemhmfpmlfbj/reviews) and give a star on Github so I can continue making useful apps.

**Comment by Gimlao** [comment]
I've seen that you include the "SD" cover ( 700x700, for example : https://f4.bcbits.com/img/a0611157579_16.jpg ), could you also include the "HD" one ( ex : https://f4.bcbits.com/img/a0611157579_10.jpg ) ?

Also, it seems that the 700x700 cover is now in the id3 tags, thanks. <3
