### ISSUE TITLE
Tracks with "/" in the title create additional folders

### ISSUE THREAD

**Issue by Gimlao** [jaymoulin/bandcamp-down-chrome-ext#28]
Example : https://music.disasterpeace.com/album/fz-side-f

It will create two folders in the « **FZ- Side F** » folder : 
« **2 - Datassette - Sync** » containing « **Glitch.mp3** »
« **12 - coda - The Clock Master (Sync** » containing « **Majesty).mp3** »

Maybe KeepTune should replace any "/" by a "-", like ":" being replaced by "-".

**Comment by jaymoulin** [comment]
This will be available in few moments on chrome webstore in version 2.2.0.

Please donate, rate this extension (https://chrome.google.com/webstore/detail/keeptune-download-on-band/oidamlgjlcjhdpkflfefcemhmfpmlfbj/reviews) and give a star on Github so I can continue making useful apps.
