### ISSUE TITLE
has Keeptune stopped working for Bandcamp in the last few days?

### ISSUE THREAD

**Issue by noisician** [jaymoulin/bandcamp-down-chrome-ext#29]
On Bandcamp, it just gets stuck after pressing download. It shows all the tracks with "waiting/cancel" next to them, but they are never downloaded.

I don't know if Bandcamp changed something? 

Or is there some way the problem is on my end? I tried removing and re-installing the extension.

**Comment by jaymoulin** [comment]
Thanks for reporting.

After tests, everything is working as expected. 

You may experience some network problem. Sometimes, bandcamp limit downloads because you exceeded quota. Try with another IP (like connecting via through your phone) or a proxy or another network etc...

**Comment by noisician** [comment]
thanks for responding! i tried again and it did work once more, so perhaps it's the quota or network issue you mentioned.
