### ISSUE TITLE
Soundcloud does not seem to trigger Keeptune

### ISSUE THREAD

**Issue by jaymoulin** [jaymoulin/bandcamp-down-chrome-ext#30]
Version 2.2.0
Unable to download this : https://soundcloud.com/oldschoolmusical/sets/osm-soundtrack

**Comment by garymm** [comment]
Has this regressed?
I'm not seeing keeptune triggered on that page today.

**Comment by jaymoulin** [comment]
No regression. Soundcloud just changed its algorithm. Since this is not related, a new issue should be opened.
