### ISSUE TITLE
"Failed - Network Error"

### ISSUE THREAD

**Issue by davetremblay** [jaymoulin/bandcamp-down-chrome-ext#31]
I get that whenever I try to download an album from KeepTune. I tried restarting the browser, the computer, uninstalling and reinstalling the extension, but nothing works.

**Comment by jaymoulin** [comment]
Duplicates #29 - Keeptune works correctly. Check you network settings, don't exceed quota and try on a new IP

**Comment by davetremblay** [comment]
I tried on different IPs on a VPN. What quota are you referring to?
Dave Tremblay

**Comment by jaymoulin** [comment]
Bandcamp has quota for listening/downloading music. If you can't listen to music on the site, you will not be able to download it. That's how Keeptune works

**Comment by davetremblay** [comment]
Ah then no I am able to stream the music just fine, but I don’t know why this network error keeps happening. It used to work properly.
Dave Tremblay

**Comment by jaymoulin** [comment]
Then you're just overquota, as refered in #29
