### ISSUE TITLE
feature request and question

### ISSUE THREAD

**Issue by c0c0c0** [jaymoulin/bandcamp-down-chrome-ext#32]
Please include album year in album folder and / or tag.  Also where is the cache location?  I am running into issues where some albums are being reported as downloaded but they will not be downloaded into the Chrome downloader and won't show up in the downloads folder.  Windows 10 pro.  Google Chrome is up to date
Version 71.0.3578.98 (Official Build) (64-bit)  One example : https://crunchpod.bandcamp.com/album/elucidation-of-instances-collection-vo-2

**Comment by jaymoulin** [comment]
Please do separates issues when you have multiple requests so others users can find what they're looking for easily.

Keeptune does not have cache system - your browser does.
If an album is displayed as downloaded you should be able to find the archive in your default download location (`CTRL + J` should show you all your downloaded files and where to find them)

Your specific URL produces the bug you describe
