### ISSUE TITLE
Extension not listed in Chrome Web Store

### ISSUE THREAD

**Issue by areyoumadlad** [jaymoulin/bandcamp-down-chrome-ext#33]
I had KeepTune installed on my browser and it was working fine. I reinstalled my OS and was setting it back up, followed the instructions at https://jaymoulin.github.io/keeptune/ and it will not let me enable the extension now, saying that it's not in the Chrome Web Store and cannot be enabled.

**Comment by jaymoulin** [comment]
You have to follow ALL steps, it cannot be installed directly from the site since chrome blocks extensions from outside of webstore for security reason

**Comment by jaymoulin** [comment]
>Go to chrome://extensions
Activate developer mode (upper left)
Reload the page (CTRL + R or CMD + R)
Drag and drop your downloaded keeptune.crx file on the extension page
Chrome should ask you if you want to install keeptune

**Comment by noconfidenceman** [comment]
I'm in the same position. Followed all the steps but Chrome won't let me switch the extension on because it's not in the webstore.
<img width="419" alt="screenshot 2019-02-25 at 6 15 57 pm" src="https://user-images.githubusercontent.com/47969798/53323419-d0246800-3929-11e9-898c-d01077602e3a.png">

**Comment by jaymoulin** [comment]
This image confirm you installed it correctly. This is just a warning because you installed it outside chrome webstore (which is the normal way to do it since Google deleted KeepTune from its webstore for policy issue)

**Comment by noconfidenceman** [comment]
But I am unable to click the toggle in the bottom right of my screenshot to activate the extension?

**Comment by jaymoulin** [comment]
Did you reload your extension page?

**Comment by noconfidenceman** [comment]
Sure did

**Comment by jaymoulin** [comment]
Then you should check on Chrome forums why it's not working :)
