### ISSUE TITLE
Extension disabled by Chrome

### ISSUE THREAD

**Issue by Gimlao** [jaymoulin/bandcamp-down-chrome-ext#36]
It seems that we can't use KeepTune anymore...

https://support.google.com/chrome_webstore/answer/2811969?hl=en

> To protect you while you browse, Chrome only lets you use extensions that have been published on the Chrome Web Store.

> If you need to use a disabled extension, you can contact the extension’s developer and ask them to upload their extension to the Chrome Web Store. This will allow you, and other people who use Chrome, to install that extension from the Chrome Web Store, or if you already have it installed, to manually re-enable it from your list of extensions.

I deleted version 2.3.0 after installing 2.3.2 then discovered that is was disabled ... ='(

**Comment by jaymoulin** [comment]
Sorry about this but I can't do anything. 
You may be able to install it on chromium or Chrome on linux (probably Firefox ) but Keeptune was banned from Chrome Webstore since it's diagnosed as a piracy tool (and I agree with them).

I may think about a solution but probably not as an extension

**Comment by Tromick** [comment]
Thank you so much for this amazing extension! I am using this since 2017.

**Comment by Technomode** [comment]
I wiped out my whole computer and from all the things I've lost this is the one that makes me sad

**Comment by jaymoulin** [comment]
Could you try with these directions: https://jaymoulin.github.io/keeptune/
