### ISSUE TITLE
Broken in Brave

### ISSUE THREAD

**Issue by barkingbandicoot** [jaymoulin/bandcamp-down-chrome-ext#37]
**Description**

Version 2.3.2 has stopped working in Brave Browser in Linux.
No update that I am aware of.
Version 2.2.1 is still working in Chromium. Is it possible to download this version?

**Steps to reproduce the issue:**
1. Load bandcamp page
2.No pop up
3.No data found

**Comment by jaymoulin** [comment]
I'm not sure that 2.2.1 will fix anything but I recompiled it
[keeptune.zip](https://github.com/jaymoulin/keeptune/files/3269690/keeptune.zip)

Precising which page you loaded would help to check what's happening.

**Comment by barkingbandicoot** [comment]
Thanks! 2.2.1 works!
