### ISSUE TITLE
Newest Release Won't Decompress

### ISSUE THREAD

**Issue by analoggue** [jaymoulin/bandcamp-down-chrome-ext#40]
The release currently linked on the releases page results in a corruption error when renamed to .zip. The release file 'keeptune.crx' appears to be HTML when opened in a text editor.

Thanks!

**Comment by jaymoulin** [comment]
I added directly the zip file to the release but please read steps slowly and carefully : 

1. Download latest version (the keeptune.zip, not the keeptune.crx nor source code zip)
1. Go to chrome://extensions
1. Activate developer mode (upper left)
1. Reload the page (CTRL + R or CMD + R)
1. Extract your downloaded keeptune.zip file in a keeptune folder
1. Click Load unpacked (upper left button)
1. Load the keeptune folder

Consider donating via sponsor links.
