### ISSUE TITLE
Adapt the extension for Firefox

### ISSUE THREAD

**Issue by Ectalite** [jaymoulin/bandcamp-down-chrome-ext#41]
Hey,
You made very good work, but as it‘s only designed to work on chrome and chromium-based browsers, do you know if you could adapt it for firefox.
Thanks for all,
Ectalite

**Comment by jaymoulin** [comment]
Thank you for your contribution.

If you find this product useful, please consider donating to help me continue creating great products.

As developing and maintaining as product is time consuming and exhausting, adapting KeepTune for Firefox was out of mind. I don't personally use Firefox and have no interest in doing such an adaptation. Plus, I'm actually selling music on Bandcamp platform and this extension is not helping me in either way.

Don't get me wrong, I understand people might be interested in this adaptation and I might adapt it. But I actually have no interest doing it.

I'll keep this issue opened for I might do it, but, unless I can be able to spend a bunch of time on it (yes, I mean financially), don't expect this to be happening soon.

**Comment by Ectalite** [comment]
Ok thanks
