### ISSUE TITLE
No Longer Possible to Download Discographies

### ISSUE THREAD

**Issue by ghost** [jaymoulin/bandcamp-down-chrome-ext#42]
Keeptune no longer gives me an option to download an artist's whole discography, but downloading by album still works. 

Recreation:
1. Install Keeptune
2. Go to artist discography, such as https://chillhop.bandcamp.com/music 

Result:
Nothing happens. Neither clicking the extension to bring up the download option works, nor is there a pop-up.

![image](https://user-images.githubusercontent.com/14362882/70766532-da75ee00-1d12-11ea-86ea-31a0cc3dc22c.png)

I do not know if this was removed on purpose, or just broke, but thank you in advance.

**Comment by jaymoulin** [comment]
Thank you for reporting this.

If you find this product useful, please consider donating to help me maintain/create great products.

Looks like Bandcamp changed its code so Keeptune (2.5.3 as I'm writing) is not compatible anymore for now.
