### ISSUE TITLE
Single tracks on bc do not trigger downloads

### ISSUE THREAD

**Issue by momiii** [jaymoulin/bandcamp-down-chrome-ext#43]
**Steps to reproduce the issue:**
Open a single track on bandcamp, like [https://il-lo.bandcamp.com/track/biome](https://il-lo.bandcamp.com/track/biome), which is not dedicated to any album. Single tracks do not have any numbered tracks.

**Describe the results you received:**
bc-downloader does not trigger. Download isn't possible.

**Describe the results you expected:**
bc-downloader should trigger to enable download.

**Additional required informations:**
Note that Albums with a numbered single track are different in behaviour (like [https://il-lo.bandcamp.com/album/alma-frameworks-remix](https://il-lo.bandcamp.com/album/alma-frameworks-remix)), they do trigger bc-downloader.

Actual Keeptune version: 2.6.0
Chrome: 80.0.3987.87

Thanks in advance!

**Comment by jaymoulin** [comment]
Thank you for reporting this. If you find this product useful, please consider donation to help me continue maintain and create great products ([![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin))
