### ISSUE TITLE
Chrome disabled manually installed extensions

### ISSUE THREAD

**Issue by mxbray** [jaymoulin/bandcamp-down-chrome-ext#44]
**Description**
Tried to install vers. 2.6.0 manually via the CRX file, but Chrome will not allow it to run. This method previously worked in the past.

Will I receive the same error with the Patreon build? Is there any way to get this working again?

**Steps to reproduce the issue:**
1. 
2.
3.

**Describe the results you received:**
https://support.google.com/chrome_webstore/answer/2811969?visit_id=637199989989389257-2849605753&p=ui_remove_non_cws_extensions&hl=en&rd=2

**Describe the results you expected:**
Expected the app to work when loading manually. 

**Additional required informations:**
Keeptune version 2.6.0

Link of the site: 
Actual Keeptune version: **Can be found in chrome "Three dot menu > More Tools > Extensions > Keeptune : <version number like 2.6.0>"**

**Comment by noconfidenceman** [comment]
I'm having the same issue. I get an alert "This extension is not listed in the Chrome Web Store and may have been added without your knowledge" and am unable to turn the extension on, even in developer mode.

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

Please check all those steps to be sure KeepTune wroks with its best conditions:
1. Check your chrome version is the latest available (My actual version: `80.0.3987.149`)
1. Check your KeepTune is the actual latest available (Public: `2.6.0`, Latest: `2.7.0`)
1. Check you downloaded ZIP version and not CRX if CRX is not working for you
1. Check your extension page is in developer mode

**Comment by mxbray** [comment]
1. I am on Chrome 80.0.3987.149
2. KeepTune public vers. 2.6.0
3. **ZIP is corrupted and will not unpack**

**Comment by jaymoulin** [comment]
Just downloaded this with no problem : http://uploaded.net/file/z8zshxn7

**Comment by mxbray** [comment]
Thank you! Confirming this does work when using the ZIP. 

**The Unarchiver** app for Mac was not able to unzip the package, but I was able to get it to work with another extraction app.

**Comment by jaymoulin** [comment]
Thank you very much for your support <3
