### ISSUE TITLE
Can't unzip public 2.6.1 zip file

### ISSUE THREAD

**Issue by Vlark** [jaymoulin/bandcamp-down-chrome-ext#45]
I've tried several times for follow the directions for unzipping the public Keeptunes 2.6.1.zip file. The file will not unzip. I keep getting an error saying the file is invalid. I have downloaded on MacOS, Windows 10, Ubuntu 18.04, and Manjaro 19 using the Chromium, Firefox, and Brave browsers and trying to unzip with a variety of unarchivers on all platforms.

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

I just tested the current available public (2.6.1) keeptune zip file on https://jaymoulin.me/me/keeptune (never download anywhere else but on this page or my patreon) and had no error extracting neither on Windows (with winrar) nor Linux ubuntu.

Please make sure your md5sum match the following `dfe9ede67fdf481cfa16094b82d848fb`

**Comment by Vlark** [comment]
If I could install it and try it out, I might be inclined to support it. But if I can't even get it to work to try it out, then why would I shove money at you? 

The checksum checks out, but it still won't unzip. I'll give winrar a try on my Windows box and see what happens.

**Comment by jaymoulin** [comment]
Just before your eyes, I released 2.6.2 public release with md5 sum `7115d5b5a794ffc12925090949e36ad3`

This archive should be extractable with the tools you're using as I changed the compression method for this archive.
