### ISSUE TITLE
Can't download anything anymore

### ISSUE THREAD

**Issue by Nowena** [jaymoulin/bandcamp-down-chrome-ext#46]
The extension no longer works. Nothing seems to trigger it; it detects no tracks, no albums, no discographies, nothing. 
I'm using Opera. Was working fine a few days ago.

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

I redacted a template for you to complete to be able to help you with this kind of trouble. Please don't ignore it for me to be able to help.

```
If you are reporting a new issue, make sure that we do not have any duplicates
already open. You can ensure this by searching the issue list for this
repository. If there is a duplicate, please close your issue and add a comment
to the existing issue instead.

If you suspect your issue is a bug, please edit your issue description to
include the BUG REPORT INFORMATION shown below. If you fail to provide this
information within 7 days, we cannot debug your issue and will close it. We
will, however, reopen it if you later provide the information.

For more information about reporting issues, see
https://github.com/jaymoulin/keeptune/blob/master/CONTRIBUTING.md

You do NOT have to include this information if this is a FEATURE REQUEST

If you find this useful, please consider starring the repo, 
rate this extension and/or donating.
People showing interest attract more attention ;)
```

**Description**

```
Briefly describe the problem you are having in a few paragraphs.
```

**Steps to reproduce the issue:**
1. 
2.
3.

**Describe the results you received:**


**Describe the results you expected:**


**Additional required informations:**

Link of the site: 
Actual Keeptune version: **Can be found in chrome "Three dot menu > More Tools > Extensions > Keeptune : <version number like X.Y.Z>"**
