### ISSUE TITLE
Frequently File Save does not raise (but sometimes it does).

### ISSUE THREAD

**Issue by mmmmna** [jaymoulin/bandcamp-down-chrome-ext#47]
Chromium:
Version 84.0.4147.105 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)

**Description**
File Save dialog often won't appear, but KT popup says 100% downloaded.
 Inconsistent file saving process

**Describe the results you received:**
https://  resonantearth.bandcamp.com/music
NOT logged in.
Click any shown release.
KT popup appears, click KT popup to download album.
Sometimes, the KT download reaches 100%, sometimes download is never reaching 100%.
When reaching 100%, KT sometimes waits minutes before raising file save dialog.
When reaching 100%, KT sometimes never raises file save dialog, waiting 10+ minutes.

Not specific to resonantearth, it happens for every Bandcamp artist I've tried with 2.7.0 for past few months, and with 2.6.0 before that..

**Describe the results you expected:**
When KT popup shows 100% downloaded, then KT should be giving the file save dialog or do not show 100%. Either it is 100% or it is not 100%. I expect that 100% downloaded means I can save the file.

**Additional required informations:**

Actual Keeptune version: 2.7.0
**Can be found in chrome "Three dot menu > More Tools > Extensions > Keeptune : <version number like X.Y.Z>"**

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).

I can't do many things about this has it's a random bug depending on Chome version. All I was able to do to "fix" this was to add "download anyway", "retry" and "cancel" buttons.
