### ISSUE TITLE
Some albums with special characters in titles do not download

### ISSUE THREAD

**Issue by Nowena** [jaymoulin/bandcamp-down-chrome-ext#48]
Albums with special characters such as "|" won't download.

Steps to reproduce the issue:
1. Go to this album: https://mhonos.bandcamp.com/album/humiliati-2012
2. Try downloading it
3. The extension acts as though the album is downloading but it doesn't actually download it at all

Albums with special characters don't download as they should because other albums normally download.

I should be able to download any album.

The version of the extension I have is 2.7.0

**Comment by jaymoulin** [comment]
Maintaining an application (answering questions, fixing bugs, adding new features...) is a hard and time consuming process. If you find this product useful and all the effort I put crafting this, I strongly encourage you to donation to help me being able to continue maintaining this and creating other great things on those platforms [![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin).
