### ISSUE TITLE
Can't download from soundcloud as of code error.

### ISSUE THREAD

**Issue by greevak** [jaymoulin/bandcamp-down-chrome-ext#49]
**Description**
![image](https://user-images.githubusercontent.com/38337258/102306098-7cf22e00-3f72-11eb-82e3-f136ae124aed.png)

line 22 says: 

`function P(a,b){return new Promise(function(c,d){var e=JSON.parse(a),f=new XMLHttpRequest;f.arguments={P:b};f.onerror=function(){return d(f.statusText)};f.open("GET",e[e.length-4]);f.onload=function(){var g=/client_id:"([^"]+)"/g.exec(f.responseText);"undefined"!==typeof g&&"undefined"!==typeof g[1]?c([g[1],f.arguments.P]):d("unable to get client id")};f.send(null)})}`

**Steps to reproduce the issue:**
1. fix the code.

**Describe the results you received:**
I wanted to download a song from soundcloud but i keep getting this error message from chrome.

**Describe the results you expected:**
work.

**Additional required informations:**
![image](https://user-images.githubusercontent.com/38337258/102305984-4b796280-3f72-11eb-884f-c2f2bf36e60d.png)

Link of the site: 
Actual Keeptune version: **2.7.1>"**

**Comment by jaymoulin** [comment]
Thank you for your issue. Keeptune support is now only continued for supporters on Patreon.

[![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin)
[![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W)
[![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin)
