### ISSUE TITLE
Unable to download at all after upgrade to 2.7.2

### ISSUE THREAD

**Issue by whispernmyghost** [jaymoulin/bandcamp-down-chrome-ext#51]
**Description**

Upgraded from 2.7.0 to 2.7.2, after upgrade not able to download from any bandcamp site. Does not display album information or "nothing to download" message.

**Steps to reproduce the issue:**
1. Remove 2.7.0 from chrome extensions
2. Remove all file folders for 2.7.0 from hard drive.
3. Download and extract 2.7.2.
4. Load unpacked files in chrome, no errors show for install.
5. Navigate to bandcamp.com and select any album with available tracks.
6. Errors displayed now for Extension
![Screen Shot 2021-02-03 at 10 28 14](https://user-images.githubusercontent.com/34548335/106777493-a7737580-660a-11eb-9bbe-8ec76e3314b5.png)

**Describe the results you received:**
Unable to download any albums or tracks see screenshot : ![Screen Shot 2021-02-03 at 10 30 37](https://user-images.githubusercontent.com/34548335/106777800-edc8d480-660a-11eb-9713-592a1dcd20d4.png)

**Describe the results you expected:**
To be able to download the album

**Additional required informations:**

Link of the site: https://allover.bandcamp.com/album/death-in-texas-2 (was previously able ot download this album)
Actual Keeptune version: 2.7.2

**Comment by jaymoulin** [comment]
Thank you for using Keeptune. As the screenshot clearly states, I live with my music or with this software and need you to support my work. If you want to continue using Keeptune, please consider upgrading to actual 2.8.0 on https://www.patreon.com/posts/keeptune-2-8-0-45563709
