### ISSUE TITLE
crx file

### ISSUE THREAD

**Issue by ilyaguam** [jaymoulin/bandcamp-down-chrome-ext#54]
yo
now your site is down and that was the only place where we could download your plugin, can you add the crx file to github please
I would like to become your patron, but this site is not available in my country(
thx for your work!

**Comment by jaymoulin** [comment]
Hello, I'm glad you like my work. 
The website is not down, it just moved to https://brands.jaymoulin.me/me/keeptune/ (temporarily). 
Can you englight me in which country Patreon is not available?
Anyway you can still support my work on https://www.buymeacoffee.com/jaymoulin and https://ko-fi.com/jaymoulin.

Thank you for your interest and support.
