### ISSUE TITLE
extension causing strange browser behaviour

### ISSUE THREAD

**Issue by zypA13510** [jaymoulin/bandcamp-down-chrome-ext#7]
Hello,

I installed your extensions a few days ago, and now I have several issues that I'd like to report:

1. It's causing problems with visitor counter on websites. Tested on my own website with a simple PHP counter, it always adds 2 visits instead of one. This is the same for those websites without session / IP records. I don't know what's going on but disabling this extension seems to solve the issue. Maybe your extension is making an additional request to the original resource? If so, would you please consider using Jquery and $ selector instead? Steps to reproduce this issue: please follow [this simple guide](http://justintadlock.com/web-design/counter) to add PHP counter to your website, or just a local apache testing site. And visit the PHP in question.

2. It's interfering with logins/form submissions on several sites. I don't know if this is related to the above issue in any way. I don't have much detail because I didn't find the root cause of this. But disabling this extension seems to solve this problem. Please investigate. Example of websites affected: https://www.alexamaster.net/ (cannot log in)

**Comment by jaymoulin** [comment]
Can you please open an issue for each problem you have so I can manage to fix what I can as soon as possible and for other users to have better informations for each issue?

**Comment by zypA13510** [comment]
Hi, I have moved the third one to a separate issue. I think 1 and 2 may be related in a way, do I have to split them into two issues?

**Comment by jaymoulin** [comment]
Thanks for your efforts, I'll try fix this ASAP

**Comment by jaymoulin** [comment]
Version should be available soon for you all through chrome webstore. Thanks for reporting and for your support.
