### ISSUE TITLE
unknown persistent error on url: shabakaandtheancestors.bandcamp.com/

### ISSUE THREAD

**Issue by jazzhead94** [jaymoulin/bandcamp-down-chrome-ext#9]
I wish I could fill in you more but I know as much about pulling up code as an ant does about magnifying glass manufacture. I recently got your extension and it works beautifully across most sites on the service but I run into the same problem with this particular URL where it'll partially download and freeze. As far as I can tell there are no pointers a where the error actually comes from; feelings of paralysis ensue.

**Comment by jaymoulin** [comment]
I can give you some information. The extension detects 9 tracks for this album, Bandcamp displays 7 tracks, but only 4 tracks are really listenable. I have to fix this issue to allow only listenable tracks to be downloaded, but I guess fixing #8 may help as well. It will result in a downloaded album with only 4 tracks

**Comment by jazzhead94** [comment]
Sorry to get back to you  so late,  I live in a pretty rural area my access is intermittent outside of term-times, this has been helpful; thanks.


________________________________
